import Link from "next/link";
import { Flame, Rocket, Sparkles, Target, Code2 } from "lucide-react";

import { auth } from "@/auth";
import { ROADMAPS } from "@/lib/mock-data/roadmaps";
import { library } from "@/lib/agents/library";
import { getLiveRoadmapStats } from "@/lib/roadmap-stats";
import { getUserProgressMaps } from "@/lib/user-progress-stats";
import { RoadmapsExplorer } from "@/components/dashboard/roadmaps-explorer";

export const metadata = { title: "Roadmaps" };
// Per-user progress means we render dynamically (auth + DB fetch).
export const dynamic = "force-dynamic";

/* The 5 highest-leverage placement-prep roadmaps surfaced as a featured row
 * at the top — mirrors the desktop sidebar's PLACEMENT_TRACKS shortcut so
 * mobile visitors (who don't see the sidebar) still discover them. */
const FEATURED = [
  { slug: "tcs-nqt-cracker", label: "TCS NQT", icon: Target },
  { slug: "service-company-cracker", label: "Service Cracker", icon: Rocket },
  { slug: "product-company-cracker", label: "Product Cracker", icon: Flame },
  { slug: "mern-stack-developer", label: "MERN Stack", icon: Code2 },
  { slug: "portfolio-builder", label: "Portfolio Builder", icon: Sparkles },
];

export default async function RoadmapsPage() {
  // Library entries (agent-generated, freshly published) come first;
  // mock roadmaps that haven't been filled by the pipeline come after.
  // When a fill run uses the mock's canonical slug, the library entry
  // replaces the mock entirely (deduped by slug).
  const [generated, liveStats, session] = await Promise.all([
    library.listRoadmaps(),
    getLiveRoadmapStats(),
    auth(),
  ]);
  const { byRoadmap } = await getUserProgressMaps(session?.user?.id);

  const generatedSlugs = new Set(generated.map((r) => r.slug));
  const remainingMocks = ROADMAPS.filter((r) => !generatedSlugs.has(r.slug));
  const merged = [...generated, ...remainingMocks];

  return (
    <div className="space-y-8">
      <header>
        <h1 className="text-3xl font-bold tracking-tight text-slate-50 sm:text-4xl">
          Roadmaps
        </h1>
        <p className="mt-2 max-w-2xl text-base text-slate-400">
          {merged.length}+ engineering paths covering every major Indian
          placement track — service companies, product startups, FAANG
          interns, GATE PSU, and the long-tail specialisations.
        </p>
        {generated.length > 0 ? (
          <p className="mt-3 inline-flex items-center gap-2 rounded-full border border-violet-500/30 bg-violet-500/10 px-3 py-1 text-xs text-violet-200">
            <span className="h-1.5 w-1.5 rounded-full bg-violet-300" />
            {generated.length} freshly generated by the agent pipeline
          </p>
        ) : null}
      </header>

      {/* Featured tracks — quick-access for the 5 highest-traffic paths.
          Mobile-friendly horizontal scroll; pinned above the full grid. */}
      <section aria-label="Featured placement tracks">
        <p className="mb-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-400">
          Featured placement tracks
        </p>
        <div className="flex gap-2 overflow-x-auto pb-1 sm:flex-wrap sm:overflow-x-visible">
          {FEATURED.map((f) => {
            const Icon = f.icon;
            return (
              <Link
                key={f.slug}
                href={`/roadmaps/${f.slug}`}
                className="group flex shrink-0 items-center gap-2 rounded-full border border-white/[0.08] bg-white/[0.02] px-4 py-2 text-xs font-medium text-slate-300 transition-colors hover:border-violet-400/30 hover:bg-white/[0.04] hover:text-white"
              >
                <Icon className="h-3.5 w-3.5 text-violet-300" />
                {f.label}
              </Link>
            );
          })}
        </div>
      </section>
      <RoadmapsExplorer
        roadmaps={merged}
        liveStats={liveStats}
        progressByRoadmap={byRoadmap}
      />
    </div>
  );
}
