import type { Company, JobPosting } from "./types";

export const COMPANIES: Company[] = [
  {
    slug: "amazon",
    name: "Amazon",
    shortName: "AMZN",
    founded: 1994,
    employees: "1.5M+",
    description:
      "Builds the world's largest e-commerce platform, AWS, devices, and digital media services.",
    techStack: ["Java", "AWS", "DynamoDB", "Python", "TypeScript", "Kotlin"],
    skillsLookFor: [
      "Strong DSA",
      "System design",
      "Java or backend depth",
      "Ownership mindset",
      "Bias for action",
    ],
    employeeQuotes: [
      {
        quote:
          "On-call is real, but the autonomy you get to ship product is rare anywhere else.",
        name: "Anika R.",
        role: "SDE-2, Bengaluru",
      },
      {
        quote:
          "The interview loop is brutal but fair. Once you're in, the bar for code review is what makes you grow.",
        name: "Karan M.",
        role: "SDE-1, Hyderabad",
      },
    ],
    relatedRoadmaps: ["java-full-stack", "ml-engineer", "devops-engineer", "aws-cloud-engineer"],
    accent: "from-amber-500 to-orange-500",
  },
  {
    slug: "google",
    name: "Google",
    shortName: "GOOG",
    founded: 1998,
    employees: "180k+",
    description:
      "Search, Cloud, Android, YouTube, Workspace — Google's product portfolio touches billions.",
    techStack: ["C++", "Go", "Java", "Python", "TypeScript", "Bigtable", "Spanner"],
    skillsLookFor: [
      "Algorithmic depth",
      "Strong CS fundamentals",
      "Distributed systems",
      "Code quality",
    ],
    employeeQuotes: [
      {
        quote:
          "The eng culture rewards careful design over quick wins. Reviews actually teach you.",
        name: "Pooja D.",
        role: "SWE, Bengaluru",
      },
    ],
    relatedRoadmaps: ["frontend-engineer", "ml-engineer", "data-engineer"],
    accent: "from-blue-500 to-cyan-500",
  },
  {
    slug: "microsoft",
    name: "Microsoft",
    shortName: "MSFT",
    founded: 1975,
    employees: "220k+",
    description:
      "Windows, Azure, Office, GitHub, VS Code — productivity and developer tools at scale.",
    techStack: ["C#", ".NET", "TypeScript", "Azure", "C++", "Python"],
    skillsLookFor: [
      "OS / systems thinking",
      "C# or modern C++",
      "Cloud architecture",
      "Strong written comms",
    ],
    employeeQuotes: [
      {
        quote:
          "GitHub + VS Code teams ship at startup pace inside a giant. Best of both worlds.",
        name: "Yash V.",
        role: "Senior SWE, Bengaluru",
      },
    ],
    relatedRoadmaps: ["devops-engineer", "ml-engineer", "aws-cloud-engineer", "cybersecurity"],
    accent: "from-cyan-500 to-blue-500",
  },
  {
    slug: "adobe",
    name: "Adobe",
    shortName: "ADBE",
    founded: 1982,
    employees: "29k+",
    description:
      "Creative Cloud, Document Cloud, Experience Cloud — the design and media giant.",
    techStack: ["C++", "JavaScript", "Java", "Python", "AWS", "Photoshop SDK"],
    skillsLookFor: [
      "C++ for desktop apps",
      "Frontend craft",
      "Performance work",
      "Cross-platform thinking",
    ],
    employeeQuotes: [
      {
        quote: "If you love graphics or imaging work, Adobe is one of the few real homes left.",
        name: "Riya P.",
        role: "MTS-1, Noida",
      },
    ],
    relatedRoadmaps: ["frontend-engineer", "ml-engineer"],
    accent: "from-rose-500 to-red-500",
  },
  {
    slug: "flipkart",
    name: "Flipkart",
    shortName: "FK",
    founded: 2007,
    employees: "30k+",
    description:
      "India's homegrown e-commerce platform, owned by Walmart. High-scale Indian consumer engineering.",
    techStack: ["Java", "Kotlin", "Go", "Kafka", "Cassandra", "AWS"],
    skillsLookFor: [
      "Java + JVM depth",
      "High-scale systems",
      "Indian-market intuition",
      "Pragmatism",
    ],
    employeeQuotes: [
      {
        quote: "Big sale day traffic is unlike anything else. You learn ops fast.",
        name: "Tanmay G.",
        role: "SDE-2, Bengaluru",
      },
    ],
    relatedRoadmaps: ["java-full-stack", "data-engineer", "flutter-mobile"],
    accent: "from-amber-500 to-yellow-500",
  },
  {
    slug: "swiggy",
    name: "Swiggy",
    shortName: "SWGY",
    founded: 2014,
    employees: "5k+",
    description:
      "India's leading food delivery and quick-commerce platform — Bengaluru's most-watched eng team.",
    techStack: ["Node.js", "TypeScript", "Java", "Go", "Kafka", "Redis"],
    skillsLookFor: [
      "Real-time systems",
      "Logistics modeling",
      "Strong product sense",
      "Speed of execution",
    ],
    employeeQuotes: [
      {
        quote: "Logistics ML touches real food. The feedback loop with reality is daily.",
        name: "Ishaan T.",
        role: "SWE-2, Bengaluru",
      },
    ],
    relatedRoadmaps: ["mern-stack", "ml-engineer", "data-engineer"],
    accent: "from-orange-500 to-red-500",
  },
  {
    slug: "razorpay",
    name: "Razorpay",
    shortName: "RZP",
    founded: 2014,
    employees: "3k+",
    description:
      "India's largest fintech infrastructure for payments and business banking.",
    techStack: ["Go", "PHP", "Node.js", "TypeScript", "Kafka", "AWS"],
    skillsLookFor: [
      "Payments domain interest",
      "Backend correctness",
      "Security mindset",
      "Calm under pressure",
    ],
    employeeQuotes: [
      {
        quote: "Money systems demand a different kind of focus. You write fewer bugs because you have to.",
        name: "Devika S.",
        role: "Backend Engineer, Bengaluru",
      },
    ],
    relatedRoadmaps: ["mern-stack", "java-full-stack", "devops-engineer"],
    accent: "from-blue-500 to-indigo-500",
  },
  {
    slug: "zerodha",
    name: "Zerodha",
    shortName: "ZRD",
    founded: 2010,
    employees: "1.3k+",
    description:
      "India's largest stockbroker. Famously product-led, low-marketing, eng-respecting culture.",
    techStack: ["Go", "Python", "PostgreSQL", "JavaScript", "Linux"],
    skillsLookFor: [
      "Open-source contributions",
      "Engineering taste",
      "Self-direction",
      "Financial markets curiosity",
    ],
    employeeQuotes: [
      {
        quote: "Tiny teams, real ownership. We don't open offices in 8 cities — we ship.",
        name: "Aditya K.",
        role: "Engineer, Bengaluru",
      },
    ],
    relatedRoadmaps: ["mern-stack", "data-engineer"],
    accent: "from-cyan-500 to-blue-500",
  },
  {
    slug: "postman",
    name: "Postman",
    shortName: "PST",
    founded: 2014,
    employees: "1k+",
    description:
      "The API platform — used by 35M+ developers worldwide. Built in India, global scale.",
    techStack: ["JavaScript", "TypeScript", "Node.js", "Electron", "AWS"],
    skillsLookFor: [
      "Developer empathy",
      "Tooling mindset",
      "Async collaboration",
      "Strong frontend",
    ],
    employeeQuotes: [
      {
        quote: "Every release ships to millions of devs. Quality bar is non-negotiable.",
        name: "Mira L.",
        role: "Frontend Engineer, Bengaluru",
      },
    ],
    relatedRoadmaps: ["frontend-engineer", "mern-stack", "react-native-mobile"],
    accent: "from-orange-500 to-pink-500",
  },
  {
    slug: "atlassian",
    name: "Atlassian",
    shortName: "TEAM",
    founded: 2002,
    employees: "12k+",
    description:
      "Jira, Confluence, Trello, Bitbucket — collaboration and dev tooling for software teams.",
    techStack: ["Java", "TypeScript", "Kotlin", "AWS", "Kafka", "PostgreSQL"],
    skillsLookFor: [
      "Strong async writing",
      "Cross-team collaboration",
      "Java backend depth",
      "Tooling sense",
    ],
    employeeQuotes: [
      {
        quote: "Remote-first done right. Code review and design docs are how the company actually runs.",
        name: "Aarav S.",
        role: "Senior Engineer, Bengaluru",
      },
    ],
    relatedRoadmaps: ["frontend-engineer", "java-full-stack", "devops-engineer"],
    accent: "from-blue-500 to-violet-500",
  },
  {
    slug: "tcs",
    name: "TCS",
    shortName: "TCS",
    founded: 1968,
    employees: "600k+",
    description:
      "Tata Consultancy Services — India's largest IT services company. Wide variety of work across BFSI, retail, telco.",
    techStack: ["Java", "C#", ".NET", "Angular", "AWS", "Mainframe"],
    skillsLookFor: [
      "Foundation in Java/.NET",
      "Process discipline",
      "Customer-facing comms",
      "Adaptability",
    ],
    employeeQuotes: [
      {
        quote: "Great first job for breadth. You see industries you'd never see at a startup.",
        name: "Nikhil R.",
        role: "Systems Engineer, Pune",
      },
    ],
    relatedRoadmaps: ["java-full-stack", "mern-stack"],
    accent: "from-blue-500 to-indigo-500",
  },
  {
    slug: "infosys",
    name: "Infosys",
    shortName: "INFY",
    founded: 1981,
    employees: "330k+",
    description:
      "Indian multinational IT services and consulting. Strong campus hiring and structured training programs.",
    techStack: ["Java", "Spring", "Angular", "AWS", "SAP", "Mainframe"],
    skillsLookFor: [
      "Enterprise Java",
      "Communication skills",
      "Willingness to learn",
      "Process orientation",
    ],
    employeeQuotes: [
      {
        quote: "Mysuru campus training was actually solid. Pivoted me from CSE student to working engineer.",
        name: "Anjali B.",
        role: "Systems Engineer, Bengaluru",
      },
    ],
    relatedRoadmaps: ["java-full-stack"],
    accent: "from-cyan-500 to-blue-500",
  },
];

export const COMPANIES_BY_SLUG: Record<string, Company> = Object.fromEntries(
  COMPANIES.map((c) => [c.slug, c]),
);

export function getCompany(slug: string): Company | undefined {
  return COMPANIES_BY_SLUG[slug];
}

export const JOB_POSTINGS: JobPosting[] = [
  {
    id: "amzn-sde1-blr",
    companySlug: "amazon",
    title: "Software Development Engineer I",
    location: "Bengaluru",
    remoteType: "Hybrid",
    experienceMin: 0,
    experienceMax: 2,
    techStack: ["Java", "AWS", "DynamoDB", "REST"],
    salaryMin: 18,
    salaryMax: 26,
    matchPct: 89,
    postedDaysAgo: 3,
    applyUrl: "#",
  },
  {
    id: "amzn-sde2-hyd",
    companySlug: "amazon",
    title: "Software Development Engineer II",
    location: "Hyderabad",
    remoteType: "Hybrid",
    experienceMin: 2,
    experienceMax: 5,
    techStack: ["Java", "Spring Boot", "AWS", "Microservices"],
    salaryMin: 32,
    salaryMax: 48,
    matchPct: 76,
    postedDaysAgo: 7,
    applyUrl: "#",
  },
  {
    id: "google-swe-blr",
    companySlug: "google",
    title: "Software Engineer, New Grad",
    location: "Bengaluru",
    remoteType: "On-site",
    experienceMin: 0,
    experienceMax: 1,
    techStack: ["C++", "Java", "Python", "Distributed Systems"],
    salaryMin: 25,
    salaryMax: 38,
    matchPct: 71,
    postedDaysAgo: 14,
    applyUrl: "#",
  },
  {
    id: "google-fe-blr",
    companySlug: "google",
    title: "Senior Frontend Engineer",
    location: "Bengaluru",
    remoteType: "Hybrid",
    experienceMin: 4,
    experienceMax: 8,
    techStack: ["TypeScript", "React", "Web Performance", "Accessibility"],
    salaryMin: 60,
    salaryMax: 95,
    matchPct: 64,
    postedDaysAgo: 5,
    applyUrl: "#",
  },
  {
    id: "msft-swe-hyd",
    companySlug: "microsoft",
    title: "Software Engineer 2",
    location: "Hyderabad",
    remoteType: "Hybrid",
    experienceMin: 2,
    experienceMax: 5,
    techStack: ["C#", ".NET", "Azure", "TypeScript"],
    salaryMin: 28,
    salaryMax: 42,
    matchPct: 68,
    postedDaysAgo: 9,
    applyUrl: "#",
  },
  {
    id: "msft-ml-blr",
    companySlug: "microsoft",
    title: "Applied Scientist II",
    location: "Bengaluru",
    remoteType: "On-site",
    experienceMin: 3,
    experienceMax: 6,
    techStack: ["Python", "PyTorch", "Azure ML", "Statistics"],
    salaryMin: 40,
    salaryMax: 65,
    matchPct: 55,
    postedDaysAgo: 12,
    applyUrl: "#",
  },
  {
    id: "adobe-swe-noida",
    companySlug: "adobe",
    title: "Member of Technical Staff (MTS-1)",
    location: "Noida",
    remoteType: "On-site",
    experienceMin: 0,
    experienceMax: 2,
    techStack: ["C++", "JavaScript", "Performance", "Adobe SDK"],
    salaryMin: 16,
    salaryMax: 24,
    matchPct: 60,
    postedDaysAgo: 4,
    applyUrl: "#",
  },
  {
    id: "fk-sde2-blr",
    companySlug: "flipkart",
    title: "SDE-II Backend",
    location: "Bengaluru",
    remoteType: "On-site",
    experienceMin: 2,
    experienceMax: 5,
    techStack: ["Java", "Kafka", "Cassandra", "Microservices"],
    salaryMin: 28,
    salaryMax: 44,
    matchPct: 82,
    postedDaysAgo: 6,
    applyUrl: "#",
  },
  {
    id: "fk-mob-blr",
    companySlug: "flipkart",
    title: "Mobile Engineer (Android)",
    location: "Bengaluru",
    remoteType: "Hybrid",
    experienceMin: 2,
    experienceMax: 4,
    techStack: ["Kotlin", "Android", "MVVM", "Coroutines"],
    salaryMin: 24,
    salaryMax: 40,
    matchPct: 58,
    postedDaysAgo: 11,
    applyUrl: "#",
  },
  {
    id: "swgy-be-blr",
    companySlug: "swiggy",
    title: "Backend Engineer",
    location: "Bengaluru",
    remoteType: "Hybrid",
    experienceMin: 1,
    experienceMax: 4,
    techStack: ["Node.js", "TypeScript", "Kafka", "Redis"],
    salaryMin: 22,
    salaryMax: 36,
    matchPct: 78,
    postedDaysAgo: 2,
    applyUrl: "#",
  },
  {
    id: "swgy-data-blr",
    companySlug: "swiggy",
    title: "Senior Data Engineer",
    location: "Bengaluru",
    remoteType: "Hybrid",
    experienceMin: 4,
    experienceMax: 7,
    techStack: ["Python", "Airflow", "Spark", "Snowflake", "dbt"],
    salaryMin: 38,
    salaryMax: 58,
    matchPct: 67,
    postedDaysAgo: 8,
    applyUrl: "#",
  },
  {
    id: "rzp-be-blr",
    companySlug: "razorpay",
    title: "Backend Engineer (Payments)",
    location: "Bengaluru",
    remoteType: "Hybrid",
    experienceMin: 2,
    experienceMax: 5,
    techStack: ["Go", "PostgreSQL", "Kafka", "AWS"],
    salaryMin: 26,
    salaryMax: 42,
    matchPct: 73,
    postedDaysAgo: 5,
    applyUrl: "#",
  },
  {
    id: "rzp-fe-blr",
    companySlug: "razorpay",
    title: "Frontend Engineer",
    location: "Bengaluru",
    remoteType: "Hybrid",
    experienceMin: 1,
    experienceMax: 4,
    techStack: ["TypeScript", "React", "Next.js", "Testing"],
    salaryMin: 22,
    salaryMax: 36,
    matchPct: 81,
    postedDaysAgo: 4,
    applyUrl: "#",
  },
  {
    id: "zrd-eng-blr",
    companySlug: "zerodha",
    title: "Engineer",
    location: "Bengaluru",
    remoteType: "On-site",
    experienceMin: 0,
    experienceMax: 6,
    techStack: ["Go", "Python", "Linux", "PostgreSQL"],
    salaryMin: 18,
    salaryMax: 50,
    matchPct: 62,
    postedDaysAgo: 13,
    applyUrl: "#",
  },
  {
    id: "pst-fe-blr",
    companySlug: "postman",
    title: "Senior Frontend Engineer",
    location: "Bengaluru",
    remoteType: "Remote",
    experienceMin: 4,
    experienceMax: 8,
    techStack: ["TypeScript", "React", "Electron", "Web Workers"],
    salaryMin: 40,
    salaryMax: 65,
    matchPct: 75,
    postedDaysAgo: 1,
    applyUrl: "#",
  },
  {
    id: "pst-be-blr",
    companySlug: "postman",
    title: "Backend Engineer (API Platform)",
    location: "Bengaluru",
    remoteType: "Remote",
    experienceMin: 3,
    experienceMax: 6,
    techStack: ["Node.js", "TypeScript", "AWS", "REST"],
    salaryMin: 32,
    salaryMax: 50,
    matchPct: 70,
    postedDaysAgo: 6,
    applyUrl: "#",
  },
  {
    id: "team-eng-blr",
    companySlug: "atlassian",
    title: "Software Engineer",
    location: "Bengaluru",
    remoteType: "Remote",
    experienceMin: 2,
    experienceMax: 5,
    techStack: ["Java", "TypeScript", "AWS", "Kafka"],
    salaryMin: 30,
    salaryMax: 50,
    matchPct: 79,
    postedDaysAgo: 10,
    applyUrl: "#",
  },
  {
    id: "team-platform-blr",
    companySlug: "atlassian",
    title: "Senior Platform Engineer",
    location: "Bengaluru",
    remoteType: "Remote",
    experienceMin: 5,
    experienceMax: 9,
    techStack: ["Kotlin", "AWS", "Kubernetes", "Terraform"],
    salaryMin: 50,
    salaryMax: 78,
    matchPct: 65,
    postedDaysAgo: 15,
    applyUrl: "#",
  },
  {
    id: "tcs-grad-pune",
    companySlug: "tcs",
    title: "Systems Engineer (Campus)",
    location: "Pune",
    remoteType: "Hybrid",
    experienceMin: 0,
    experienceMax: 1,
    techStack: ["Java", ".NET", "SQL"],
    salaryMin: 4,
    salaryMax: 7,
    matchPct: 68,
    postedDaysAgo: 21,
    applyUrl: "#",
  },
  {
    id: "infy-grad-blr",
    companySlug: "infosys",
    title: "Systems Engineer",
    location: "Bengaluru",
    remoteType: "On-site",
    experienceMin: 0,
    experienceMax: 1,
    techStack: ["Java", "Spring", "SQL"],
    salaryMin: 4,
    salaryMax: 6,
    matchPct: 65,
    postedDaysAgo: 18,
    applyUrl: "#",
  },
];
