import type { Roadmap } from "./types";

/**
 * Roadmaps aligned with the current SUBJECTS list — only references to
 * subjects that actually exist (and have content) are kept. Roadmaps whose
 * core curriculum (Python / ML / Data Engineering) is no longer covered have
 * been removed entirely.
 */

export const ROADMAPS: Roadmap[] = [
  {
    slug: "genai-developer",
    title: "GenAI Developer (Top 2% Path)",
    description:
      "Math foundations → transformers → RAG → agents → fine-tuning → multimodal → MLOps → specialization. The complete top-2% Gen AI engineer path.",
    longDescription:
      "12-15 month deliberate-practice roadmap — IIT-level depth in Hinglish. Phase 0 (math + Python mastery) → Phase 1 (classical ML + DL) → Phase 2 (transformers & LLM internals — the differentiator) → Phase 3 (LLM apps, RAG) → Phase 4 (AI agents) → Phase 5 (fine-tuning & customization) → Phase 6 (multimodal — VLMs, diffusion, audio/video) → Phase 7 (production, MLOps, serving at scale) → Phase 8 (specialization + top-2% habits). Outcome: production-grade Gen AI Engineer who can build, deploy, fine-tune, and optimize LLM-powered systems at scale. Salary band: ₹18-32 LPA fresher, ₹38-80 LPA at 2-5 years experience at top product companies.",
    category: "Data & ML",
    difficulty: "Advanced",
    durationMonths: 14,
    subjectsCount: 21,
    topicsCount: 90,
    rating: 4.9,
    enrolled: 9420,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "Python",
      "PyTorch",
      "Transformers",
      "RAG",
      "Agents (LangGraph)",
      "Fine-tuning (LoRA/DPO)",
      "vLLM",
      "MLOps",
      "Multimodal",
    ],
    companies: ["razorpay", "postman", "swiggy", "amazon"],
    whyThis: [
      "Highest-paying engineering role in India right now. Fresher CTC ₹18–32 LPA at top product cos; mid-level ₹38–80 LPA.",
      "Skills are scarce — every product company is shipping AI features and scrambling for talent.",
      "Pairs deep ML knowledge with practical engineering — both transfer cleanly to other roles if you pivot later.",
      "Top-2% engineers (transformers cold, papers weekly, ship in production) command 2-3x median compensation.",
    ],
    subjectSlugs: [
      "genai-math",
      "genai-programming",
      "genai-classical-ml",
      "genai-deep-learning",
      "genai-transformers",
      "genai-llm-apis",
      "genai-rag",
      "genai-frameworks",
      "genai-agent-foundations",
      "genai-multi-agent",
      "genai-finetuning",
      "genai-vlm",
      "genai-diffusion",
      "genai-audio-video",
      "genai-backend",
      "genai-serving",
      "genai-llmops",
      "genai-cloud-infra",
      "genai-safety",
      "genai-specialization",
      "genai-top2-habits",
    ],
  },
  {
    slug: "senior-frontend-engineer",
    title: "Senior Frontend Engineer (React + Performance)",
    description:
      "HTML, CSS, JavaScript deep, React, Next.js, accessibility, performance — frontend craft for product teams.",
    longDescription:
      "Become the frontend engineer companies fight over. Deep HTML, CSS, JavaScript, React, Next.js, performance budgets, accessibility, security, PWAs, and shipping pixel-perfect UI. Salary: ₹12-24 LPA fresher, ₹28-60 LPA at 2-5 years. Most 'frontend devs' only know React basics — engineers who deeply understand Core Web Vitals, a11y, and design systems pull a 30%+ premium at product cos.",
    category: "Web Development",
    difficulty: "Intermediate",
    durationMonths: 5,
    subjectsCount: 13,
    topicsCount: 60,
    rating: 4.9,
    enrolled: 8420,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Next.js",
      "Accessibility",
      "Core Web Vitals",
      "Testing",
    ],
    companies: ["razorpay", "atlassian", "postman", "swiggy"],
    whyThis: [
      "Frontend specialists with perf + a11y are scarce in India — Razorpay, Postman, Swiggy pay 30%+ premium for this profile.",
      "Modern JS + React skills transfer across web, mobile (RN), and desktop (Electron).",
      "Highest-leverage role in product companies — what users actually feel, you build.",
    ],
    subjectSlugs: [
      "html-fundamentals",
      "css-fundamentals",
      "javascript-deep",
      "react-complete",
      "nextjs-modern",
      "frontend-api-integration",
      "accessibility-seo",
      "frontend-performance",
      "frontend-security",
      "frontend-testing",
      "pwa-fundamentals",
      "frontend-deployment",
      "git-version-control",
    ],
  },
  {
    slug: "java-full-stack",
    title: "Java Full Stack Developer",
    description:
      "Spring Boot APIs, React frontends, microservices, and cloud deployment — the most reliable hire-to-CTC path.",
    longDescription:
      "From core Java to deploying Spring Boot apps with React frontends. Covers Java fundamentals, Spring Framework + Spring Boot, microservices, JPA, REST APIs, React, SQL/NoSQL, Docker, and cloud basics. Salary: ₹14-26 LPA fresher at product cos, ₹28-50 LPA at 2-5 years. Most consistent demand across MNCs and Indian product companies. Amazon, Flipkart, Atlassian, Razorpay hire continuously at this profile.",
    category: "Web Development",
    difficulty: "Intermediate",
    durationMonths: 6,
    subjectsCount: 14,
    topicsCount: 90,
    rating: 4.8,
    enrolled: 11240,
    thumbnailAccent: "from-orange-500 to-red-500",
    skills: [
      "Java",
      "Spring Boot",
      "Microservices",
      "React",
      "SQL",
      "Docker",
      "Cloud",
      "REST APIs",
    ],
    companies: ["amazon", "flipkart", "atlassian", "razorpay"],
    whyThis: [
      "Most consistent demand across MNCs and Indian product cos — supply chain stable, hiring continuous.",
      "Salary floor is highest at fresher level (₹14–26 LPA at product cos) — best risk-adjusted path.",
      "Java + Spring is the 'boring but bulletproof' choice — pairs well with React for genuine full-stack confidence.",
    ],
    progressPct: 34,
    subjectSlugs: [
      "java-fundamentals",
      "spring-boot-basics",
      "microservices",
      "database-sql",
      "database-nosql",
      "react-complete",
      "frontend-api-integration",
      "system-design-basics",
      "lld-design",
      "docker-containers",
      "cloud-fundamentals",
      "git-version-control",
      "software-testing",
      "clean-code-solid",
      "design-patterns",
    ],
  },
  {
    slug: "cloud-devops-engineer",
    title: "Cloud / DevOps Engineer",
    description:
      "Docker, Kubernetes, CI/CD, observability, cloud platforms — keep production alive at scale.",
    longDescription:
      "Become the engineer who keeps production alive. Master Docker, Kubernetes, CI/CD pipelines, server deployment, AWS + GCP, monitoring with Prometheus/Grafana, and system design at scale. Salary: ₹13-25 LPA fresher, ₹30-65 LPA at 2-5 years. Cloud-certified engineers with hands-on K8s experience get bidding wars at startups and MNCs.",
    category: "DevOps & Cloud",
    difficulty: "Advanced",
    durationMonths: 7,
    subjectsCount: 11,
    topicsCount: 50,
    rating: 4.8,
    enrolled: 5180,
    thumbnailAccent: "from-cyan-500 to-blue-500",
    skills: [
      "Docker",
      "Kubernetes",
      "CI/CD",
      "AWS",
      "GCP",
      "Prometheus",
      "Grafana",
      "System Design",
    ],
    companies: ["amazon", "microsoft", "atlassian", "razorpay"],
    whyThis: [
      "Cloud-native is now table stakes — every product company needs platform engineers. Demand outpaces supply 3:1.",
      "Salary ramp is fast: ₹13–25 LPA fresher → ₹30–65 LPA at 2–5 years experience.",
      "Hands-on production debugging is the moat that AI can't replace easily.",
    ],
    subjectSlugs: [
      "docker-containers",
      "kubernetes-orchestration",
      "cicd-pipelines",
      "server-deployment",
      "cloud-fundamentals",
      "cloud-platforms",
      "system-design-basics",
      "system-design-advanced",
      "messaging-systems",
      "monitoring-observability",
      "git-version-control",
    ],
  },
  // =====================================================================
  // DATA ANALYST TOP 2% — full path: SQL → Python → Stats → A/B → Causal → BI → Domain
  // =====================================================================
  {
    slug: "data-analyst-top2",
    title: "Data Analyst (Top 2% Path)",
    description:
      "SQL → Python → Statistics → A/B testing → Causal inference → BI → Storytelling. Become the analyst who drives decisions worth crores.",
    longDescription:
      "10–12 month deliberate-practice roadmap — IIT-level depth in Hinglish. Phase 0 (business + statistics foundations) → Phase 1 (SQL mastery — window functions, cohorts, funnels) → Phase 2 (Python + Pandas for analytics) → Phase 3 (Excel + Tableau/Power BI + storytelling) → Phase 4 (A/B testing + causal inference — the real top-2% moat) → Phase 5 (ML for analysts — churn, LTV, forecasting) → Phase 6 (modern data stack — Snowflake, dbt, Git) → Phase 7 (domain depth — product, marketing, finance) → Phase 8 (stakeholder influence + top-2% habits). Outcome: a strategic analyst who turns ambiguous business questions into ₹-quantified recommendations. Salary band: ₹8–18 LPA fresher, ₹22–55 LPA at 2-5 years at top product companies (Flipkart, Razorpay, Swiggy, Zomato, Paytm, Meesho).",
    category: "Data & ML",
    difficulty: "Intermediate",
    durationMonths: 11,
    subjectsCount: 16,
    topicsCount: 70,
    rating: 4.9,
    enrolled: 7820,
    thumbnailAccent: "from-cyan-500 to-blue-500",
    skills: [
      "SQL (window functions, cohorts)",
      "Python (Pandas, NumPy)",
      "Statistics & A/B Testing",
      "Causal Inference",
      "Tableau / Power BI",
      "Excel / DAX",
      "dbt + Snowflake",
      "Storytelling with Data",
    ],
    companies: ["razorpay", "swiggy", "amazon", "atlassian"],
    whyThis: [
      "Highest decision-making leverage outside of leadership — top analysts shape product, pricing, marketing strategy directly with data.",
      "Salary ramp: ₹8–18 LPA fresher → ₹22–55 LPA at 2–5 years at product companies. Senior IC analysts with experimentation + causal skills hit ₹60–90 LPA.",
      "Most analysts are 'dashboard monkeys'. The top 2% — who can run experiments, prove causation, and quantify impact in ₹ — are 5x rarer and 3x better paid.",
      "Skills compound: SQL + stats + business sense transfer cleanly to Data Scientist, Product Manager, or Analytics Engineer roles.",
    ],
    subjectSlugs: [
      "da-business-fundamentals",
      "da-statistics-foundations",
      "da-sql-mastery",
      "da-python-analytics",
      "da-excel-mastery",
      "da-bi-tools",
      "da-data-storytelling",
      "da-ab-testing",
      "da-causal-inference",
      "da-ml-for-analysts",
      "da-data-warehousing",
      "da-dbt-modeling",
      "da-product-analytics",
      "da-marketing-finance-analytics",
      "da-stakeholder-influence",
      "da-top2-habits",
    ],
  },
  {
    slug: "product-company-cracker",
    title: "Product Company Cracker (Razorpay / Flipkart / Zomato)",
    description:
      "DSA + System Design + LLD + clean code. The exact stack to clear SDE-1 / SDE-2 interviews at Indian product startups (8–25 LPA band).",
    longDescription:
      "5-7 month focused interview-prep roadmap for engineers targeting Indian product companies. Stack: a database deep-dive (SQL + indexes), system design (HLD basics → advanced — caching, sharding, CAP), the most-asked LLD problems (Parking Lot, Splitwise, BookMyShow + 27 more), clean code & SOLID, and design patterns. Pair this with the DSA practice section (460 problems) and you have the exact prep map for 25 LPA at Razorpay, Flipkart, Swiggy, Zomato, Postman, Cred, Atlan. Not for service companies — for that, use the upcoming Service Cracker roadmap.",
    category: "Interview Prep",
    difficulty: "Intermediate",
    durationMonths: 6,
    subjectsCount: 6,
    topicsCount: 38,
    rating: 4.9,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "DSA fluency",
      "SQL + indexes",
      "System Design (HLD)",
      "Low-Level Design (LLD)",
      "SOLID",
      "Design Patterns",
    ],
    companies: ["razorpay", "flipkart", "swiggy", "zomato", "postman"],
    whyThis: [
      "Indian product startups pay ₹8-25 LPA at SDE-1, ₹25-50 LPA at SDE-2 — and they all use the same interview format: DSA + LLD + HLD + behavioural.",
      "LLD is the round most engineers skip prep for and fail. This roadmap front-loads it.",
      "Built around the exact subjects asked at Razorpay, Flipkart, Swiggy interview cycles in 2026.",
      "Pair it with the practice section (460 DSA problems, multi-language runner) and the cohort weekly leaderboard.",
    ],
    subjectSlugs: [
      "database-sql",
      "dbms-complete",
      "os-complete",
      "networks-complete",
      "system-design-basics",
      "lld-design",
      "system-design-advanced",
      "clean-code-solid",
      "design-patterns",
      "resume-behavioural",
    ],
  },
  {
    slug: "service-company-cracker",
    title: "Service Company Cracker (TCS NQT / Infosys / Wipro)",
    description:
      "Aptitude (Quant + Logical + Verbal) + DSA + DBMS + OS + Networks + OOPS + Resume + Git. The complete prep stack for TCS NQT, Infosys SP, Wipro WILP, Cognizant GenC, Capgemini Pseudocode (3-7 LPA band).",
    longDescription:
      "3-4 month focused roadmap for tier-2/3 college students targeting Indian service companies. The hiring funnel is: aptitude test → coding round → HR round → offer. Most students fail at aptitude, not coding — we front-load all three aptitude legs (Quantitative + Logical + Verbal), then pair with DSA practice (460 problems, multi-language runner), the core CS subjects every interview asks about (DBMS for ACID/indexes, OS for processes/scheduling/deadlock, Networks for OSI/TCP/HTTP/DNS), OOP via Core Java, Git, and the resume + behavioural STAR module that decides who walks into the HR round prepared. Outcome: ready for any service-company campus drive within 90 days, then upskill from there into product-company prep.",
    category: "Interview Prep",
    difficulty: "Beginner",
    durationMonths: 4,
    subjectsCount: 12,
    topicsCount: 83,
    rating: 4.8,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "Aptitude (Quant + Logical + Verbal)",
      "DSA fundamentals",
      "DBMS",
      "Operating Systems",
      "Computer Networks",
      "OOP via Java",
      "Git",
      "Resume + Behavioural STAR",
    ],
    companies: ["tcs", "infosys", "wipro", "cognizant", "capgemini"],
    whyThis: [
      "TCS NQT alone has 1M+ aspirants per year — and over 60% fail at the aptitude round, not coding.",
      "Service companies hire at 3-7 LPA fresher and add ~30% on getting promoted to product/SDE-2 paths within 2-3 years.",
      "Front-loads aptitude (the gate) — Quant + Logical + Verbal — then layers core CS (DBMS / OS / Networks) every tech interview asks about.",
      "Resume + Behavioural module closes the gap that rejects half of qualified candidates before the technical round.",
      "After clearing this, the upgrade path to Product Company Cracker is one extra LLD subject.",
    ],
    subjectSlugs: [
      "aptitude-quant",
      "aptitude-logical",
      "aptitude-verbal",
      "java-fundamentals",
      "dbms-complete",
      "os-complete",
      "networks-complete",
      "database-sql",
      "git-version-control",
      "mock-interview-comm",
      "hdfc-banking-tech",
      "resume-behavioural",
    ],
  },
  {
    slug: "tcs-nqt-cracker",
    title: "TCS NQT Cracker — Volume Play (3-9 LPA)",
    description:
      "The exact prep stack for India's largest engineering test (1M+ aspirants/year). Aptitude × 3 + Python (TCS coding round) + TCS-specific playbook + Resume + behavioural — 60 days end-to-end.",
    longDescription:
      "TCS NQT is the single biggest engineering placement gateway in India — 1M+ candidates per year. This roadmap front-loads the exact mix that clears Foundation + Advanced sections: all three aptitude legs (Quant, Logical, Verbal), Python mastery for the hands-on coding round (Python is the LOC-fastest allowed language), the TCS-specific playbook covering test structure, email writing, HR round, and the 60-day prep cadence. After this you can attempt Ninja (3.36 LPA), Digital (7 LPA), Prime (9 LPA), or even CodeVita. Pair with the resume + behavioural module for the post-test rounds.",
    category: "Interview Prep",
    difficulty: "Beginner",
    durationMonths: 2,
    subjectsCount: 6,
    topicsCount: 50,
    rating: 4.9,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "TCS NQT structure",
      "Aptitude (Quant + Logical + Verbal)",
      "Python (TCS coding round)",
      "Email writing",
      "TCS HR round + bond strategy",
      "Resume + Behavioural STAR",
    ],
    companies: ["tcs"],
    whyThis: [
      "1M+ aspirants per year — owning this prep means owning India's largest placement funnel.",
      "Score thresholds (Ninja → Digital → Prime → CodeVita) are deterministic — this roadmap targets each band.",
      "Front-loads aptitude (the gate) + Python (the coding round) + the playbook (the structure / strategy).",
      "60-day cadence is realistic — daily 3 hours during placement season.",
    ],
    subjectSlugs: [
      "aptitude-quant",
      "aptitude-logical",
      "aptitude-verbal",
      "python-mastery",
      "tcs-nqt-playbook",
      "resume-behavioural",
    ],
  },
  {
    slug: "mern-stack-developer",
    title: "MERN Stack Developer — Indian Startups (8-25 LPA)",
    description:
      "MongoDB + Express + React + Node — the #1 hired stack at Indian product startups. JS/TS + React/Next + Node/Express + Mongo/SQL + system design + LLD + deployment. End-to-end ship-ready.",
    longDescription:
      "MERN is the highest-volume specialisation for Indian product startups (Razorpay, Zomato, Swiggy, Cred, Postman, Atlan). This roadmap covers both halves of the stack: the frontend (JS/TS deep, React, Next.js, API integration, performance, testing, deployment) and the backend (Node + Express, REST design, JWT auth, validation, DB integration with Mongo + Postgres). System design + LLD + clean code + design patterns close the senior-engineer gap. Pair with DSA practice + resume + behavioural for interview rounds.",
    category: "Web Development",
    difficulty: "Intermediate",
    durationMonths: 6,
    subjectsCount: 15,
    topicsCount: 106,
    rating: 4.9,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "JavaScript / TypeScript",
      "React + Next.js",
      "Node.js + Express",
      "MongoDB + Postgres",
      "REST + JWT auth",
      "Testing + Deployment",
      "System Design + LLD",
    ],
    companies: ["razorpay", "zomato", "swiggy", "postman", "cred"],
    whyThis: [
      "MERN is hiring volume #1 at Indian product startups — every Series A+ startup has 5-15 open MERN roles.",
      "JS/TS one language across stack = faster ramp than Java + Python + Go combos.",
      "Pairs nicely with DSA practice (JS allowed in 2/3 Indian startup DSA rounds) + LLD subject from this catalog.",
      "Outcome: ready for SDE-1 / SDE-2 interviews at Razorpay / Zomato / Swiggy / Cred / Postman in 5-6 months.",
    ],
    subjectSlugs: [
      "html-fundamentals",
      "css-fundamentals",
      "javascript-deep",
      "react-complete",
      "nextjs-modern",
      "frontend-api-integration",
      "frontend-testing",
      "frontend-deployment",
      "nodejs-backend",
      "database-sql",
      "database-nosql",
      "mongodb-deep-dive",
      "system-design-basics",
      "lld-design",
      "git-version-control",
    ],
  },
  {
    slug: "android-developer",
    title: "Android Developer (Kotlin + Compose) — 6-22 LPA",
    description:
      "Modern Android stack: Kotlin, Jetpack Compose, ViewModel + StateFlow (UDF), Room, Retrofit, Hilt, Coroutines, Play Store deployment. The exact Android curriculum that gets hired at Swiggy/Zomato/PhonePe.",
    longDescription:
      "Indian consumer products live or die on Android — 78% market share, 600M+ users. Swiggy, Zomato, PhonePe, Paytm, CRED hire heavily for Android, but tier-2/3 colleges almost never teach modern Android (Compose, StateFlow, Hilt). This roadmap front-loads the exact stack hiring managers ask about in 2026: Kotlin essentials, Jetpack Compose-first UI, ViewModel + UDF state, Room persistence, Retrofit networking, Hilt DI, Coroutines + Flow. Pair with system design + LLD + networks for the architecture round.",
    category: "Mobile",
    difficulty: "Intermediate",
    durationMonths: 5,
    subjectsCount: 6,
    topicsCount: 50,
    rating: 4.9,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "Kotlin",
      "Jetpack Compose",
      "ViewModel + StateFlow",
      "Room + Retrofit",
      "Hilt DI",
      "Coroutines + Flow",
      "Play Store deployment",
    ],
    companies: ["swiggy", "zomato", "phonepe", "paytm", "cred"],
    whyThis: [
      "Android hiring at Indian consumer products is consistent, not cyclical — Swiggy/Zomato/PhonePe always hiring.",
      "Modern Compose-first stack is what 2026 interviews probe — outdated XML-View tutorials don't get you hired.",
      "LLD knowledge from this catalog directly powers Android architecture round (MVI / Repository / Use case).",
      "Outcome: ready for Android SDE-1 / SDE-2 at Indian consumer products in 4-5 months.",
    ],
    subjectSlugs: [
      "android-kotlin",
      "java-fundamentals",
      "networks-complete",
      "lld-design",
      "system-design-basics",
      "git-version-control",
    ],
  },
  {
    slug: "ml-engineer",
    title: "ML Engineer / Data Scientist (12-50 LPA)",
    description:
      "Math + classical ML + DL intro + training pipelines + evaluation + MLOps + business framing. Distinct from Data Analyst (analytics) and GenAI Engineer (LLMs). Razorpay risk, Swiggy ETA, CRED fraud teams hire here.",
    longDescription:
      "Indian product companies have dedicated ML / Data Science teams that hire separately from Data Analyst and GenAI roles. Razorpay risk modelling, Swiggy delivery-time estimation, Zomato recommendation, CRED fraud detection, Hotstar churn prediction — every team needs MLE/DS who can train classical models, productionise via MLOps, and translate business KPIs into model metrics. This roadmap closes that gap with: just-enough math, the full classical ML stack (linear → trees → boosting → SVM → clustering), deep-learning intro, the full training pipeline, evaluation rigour (precision-recall trade-offs at Indian product scale), MLOps (FastAPI serving + MLflow + drift), and business framing.",
    category: "Data & ML",
    difficulty: "Advanced",
    durationMonths: 8,
    subjectsCount: 6,
    topicsCount: 50,
    rating: 4.9,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "Python + Pandas",
      "Classical ML (sklearn / XGBoost / LightGBM)",
      "Deep Learning intro",
      "Evaluation + CV + Optuna",
      "MLOps (FastAPI / MLflow / Feast)",
      "Business framing",
    ],
    companies: ["razorpay", "swiggy", "zomato", "cred", "hotstar"],
    whyThis: [
      "12-25 LPA fresher MLE at Indian product cos, 25-50 LPA at 2-4 yrs experience.",
      "Distinct from Data Analyst (no model shipping) and GenAI (LLM-only) — own role identity.",
      "Pairs Python mastery with the math + statistics that interviews actually probe (A/B test design, Bayes', regularisation derivation).",
      "MLOps coverage closes the gap most candidates have between 'trained a model in a notebook' and 'shipped one in production'.",
    ],
    subjectSlugs: [
      "python-mastery",
      "ml-engineer",
      "database-sql",
      "system-design-basics",
      "genai-deep-learning",
      "git-version-control",
    ],
  },
  {
    slug: "infosys-sp-cracker",
    title: "Infosys SP / Power Programmer Cracker (8-11.25 LPA)",
    description:
      "Volume #2 after TCS NQT (~500k aspirants/year). Aptitude × 3 + Pseudocode + Coding + Infosys-specific HR + Resume. The exact prep stack for Infosys SP (8 LPA) and Power Programmer (11.25 LPA).",
    longDescription:
      "Infosys SP test (HackerEarth platform) is the second-largest single placement test in India after TCS NQT. The salary delta between regular SE (3.5 LPA) and SP (8 LPA) or PP (11.25 LPA) is enormous — clearing this test alone doubles or triples your fresher offer. This roadmap pairs the existing aptitude triplet with Python (HackerEarth coding round), the Infosys-specific playbook covering pseudocode rounds (the secret weapon — most students under-prep this), the coding patterns, the technical-flavoured HR (Infosys probes CS fundamentals harder than TCS), and the post-test rounds.",
    category: "Interview Prep",
    difficulty: "Beginner",
    durationMonths: 3,
    subjectsCount: 7,
    topicsCount: 60,
    rating: 4.9,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "Aptitude (Quant + Logical + Verbal)",
      "Python (HackerEarth)",
      "Pseudocode reasoning",
      "Infosys SP / PP coding patterns",
      "Technical-flavoured HR",
      "Resume + Behavioural STAR",
    ],
    companies: ["infosys"],
    whyThis: [
      "~500k aspirants per year — the second-biggest engineering placement filter in India.",
      "Salary delta SE → SP → PP is 2-3× — clearing this test changes career arc.",
      "Pseudocode round is the differentiator — fewer students prep it, so it's where the SP/PP cutoff falls.",
      "Pairs naturally with TCS NQT prep (aptitude is shared) — students often attempt both.",
    ],
    subjectSlugs: [
      "aptitude-quant",
      "aptitude-logical",
      "aptitude-verbal",
      "python-mastery",
      "infosys-sp-playbook",
      "dbms-complete",
      "resume-behavioural",
    ],
  },
  {
    slug: "portfolio-builder",
    title: "Portfolio Builder — Resume + Projects + Open Source",
    description:
      "What gets you hired: 20 portfolio-grade capstones with build steps + open source contribution playbook + resume + LinkedIn + STAR. This roadmap is independent — pair with any specialisation track.",
    longDescription:
      "Recruiters scan GitHub before reading your resume. EngiNerd's other roadmaps cover what you should KNOW; this one covers what you should SHIP. The 20-project capstone bank gives portfolio-grade ideas across MERN, backend, mobile, ML, DevOps, systems, and GenAI — each with stack, build outline, time estimate, and a resume-ready bullet. The open source contribution guide shows the 4 flagship paths (GSoC, MLH Fellowship, LFX Mentorship, Hacktoberfest) and how to build maintainer reputation in 6 months. Resume + Behavioural module closes the loop. Outcome: hire-ready GitHub + LinkedIn presence by graduation.",
    category: "Portfolio",
    difficulty: "Beginner",
    durationMonths: 4,
    subjectsCount: 7,
    topicsCount: 54,
    rating: 4.9,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "Capstone project shipping",
      "Open source contribution",
      "Resume + LinkedIn + STAR",
      "GitHub portfolio polish",
      "Build cadence",
    ],
    companies: ["razorpay", "postman", "swiggy", "zomato", "cred"],
    whyThis: [
      "Layer 4 of placement-readiness has been at zero coverage. This roadmap is the highest-impact gap-fill.",
      "Recruiters spend 6 seconds on a resume — a deployed live link wins more than 100 LeetCode solutions.",
      "OSS contributions are the strongest hireability signal Indian students consistently underuse.",
      "Pairs with any specialisation track — a Java Full Stack student does these in parallel with the technical roadmap.",
    ],
    subjectSlugs: [
      "capstone-bank",
      "open-source-guide",
      "gsoc-india-playbook",
      "hackathons-bip-freelancing",
      "git-version-control",
      "resume-behavioural",
      "final-layer-closures",
    ],
  },
  {
    slug: "data-engineer",
    title: "Data Engineer (14-65 LPA — Razorpay/Swiggy/Zomato)",
    description:
      "Modern data stack — SQL deep + warehousing + Spark + Airflow + dbt + Kafka + data quality. Distinct role at Indian product co data orgs. Salary band 14-30 LPA fresher, 35-65 LPA at 3-5 yrs.",
    longDescription:
      "Data Engineering is one of the fastest-growing roles in 2026 — every Indian product co (Razorpay, Swiggy, Zomato, CRED, Paytm) has a dedicated DE org separate from ML/Analytics. The pipeline is: SQL fluency → DBMS internals → warehousing concepts (star schema, SCD) → Spark for batch processing → Airflow for orchestration → dbt for analytics-engineering → Kafka for streaming → data quality + observability. Pair with Python mastery (the lingua franca of DE) and the existing system-design subjects.",
    category: "Data & ML",
    difficulty: "Advanced",
    durationMonths: 7,
    subjectsCount: 7,
    topicsCount: 60,
    rating: 4.9,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "SQL deep + warehousing",
      "Apache Spark (PySpark)",
      "Airflow + dbt",
      "Kafka + streaming",
      "Data quality + lineage",
      "Cost-aware query design",
    ],
    companies: ["razorpay", "swiggy", "zomato", "cred", "paytm"],
    whyThis: [
      "14-30 LPA fresher DE at Indian product cos, 35-65 LPA at 3-5 yrs.",
      "Distinct from Data Analyst (no pipelines) and ML Engineer (no warehousing) — own role identity.",
      "Indian product co data orgs are growing faster than backend orgs in 2026.",
      "Pairs Python + SQL + cloud-platform fluency — broadly applicable skills if you later pivot.",
    ],
    subjectSlugs: [
      "python-mastery",
      "database-sql",
      "dbms-complete",
      "data-engineer",
      "system-design-basics",
      "cloud-platforms",
      "git-version-control",
    ],
  },
  {
    slug: "qa-sdet-cracker",
    title: "QA / SDET — Underrated Entry Point (6-25 LPA)",
    description:
      "The most-underrated entry into Indian tech. Manual QA + Playwright/Cypress + API testing + k6 perf + Appium + CI integration. Strong 2-yr upgrade path to SDE roles at Razorpay/Postman/Swiggy.",
    longDescription:
      "QA / SDET is the single most-underrated entry point into Indian tech hiring. Tier-2/3 students don't realise it has lower interview bar than SDE roles, yet stronger 2-3 yr upgrade ladders to SDE-2. Salary 6-15 LPA fresher SDET, 12-25 LPA after 2 yrs at Razorpay / Postman / Swiggy / Zomato. This roadmap front-loads manual QA, automation (Playwright is the modern winner), API testing, performance testing, mobile, the SDET test-infra role, CI integration, plus the QA → SDET → SDE upgrade path. Pair with one backend language deep + LLD for the SDE pivot.",
    category: "Interview Prep",
    difficulty: "Beginner",
    durationMonths: 5,
    subjectsCount: 6,
    topicsCount: 45,
    rating: 4.8,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "Manual QA fundamentals",
      "Playwright / Cypress automation",
      "API + performance testing",
      "Mobile testing (Appium)",
      "CI integration",
      "Test infrastructure",
    ],
    companies: ["razorpay", "postman", "swiggy", "zomato", "cred"],
    whyThis: [
      "Lowest interview-bar entry into Indian product cos (6-15 LPA fresher).",
      "Strong 2-yr SDET → SDE upgrade ladder (Razorpay / Atlan have explicit ladder).",
      "Critical for tier-2/3 students who can't crack SDE round 1 immediately.",
      "Modern Playwright-first stack is what 2026 SDET interviews probe.",
    ],
    subjectSlugs: [
      "qa-sdet",
      "javascript-deep",
      "python-mastery",
      "lld-design",
      "git-version-control",
      "resume-behavioural",
    ],
  },
  {
    slug: "off-campus-cracker",
    title: "Off-Campus Drive Cracker — For Tier-3 / No-Placement-Cell",
    description:
      "Find jobs without a placement cell. LinkedIn cold-outreach + recruiter messages + ATS hacks + referral plays + naukri/instahyre tactics + FAANG India intern programs (Google STEP / Amazon WoW / MS Engage). Independent of campus.",
    longDescription:
      "40% of Indian product co hires are off-campus. Tier-3 colleges typically have weak/no placement cells — ₹3 LPA service company cap if you depend on them. This roadmap IS the campus those students don't have. Off-campus playbook covers LinkedIn cold-outreach (5 model DMs), recruiter messages, referral plays, ATS keyword hacks, year-by-year strategy. Pair with FAANG India intern playbook (Google STEP / Amazon WoW / Microsoft Engage / Meta MUE for the top-1% target) and the resume + behavioural module to win interviews once you land them.",
    category: "Interview Prep",
    difficulty: "Beginner",
    durationMonths: 4,
    subjectsCount: 10,
    topicsCount: 74,
    rating: 4.9,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "LinkedIn cold-outreach",
      "Referral playbook",
      "ATS keyword optimisation",
      "Job board strategy",
      "FAANG India intern programs",
      "GSoC / LFX / Outreachy mentorship",
      "Resume + Behavioural STAR",
    ],
    companies: ["razorpay", "swiggy", "zomato", "cred", "google", "amazon", "microsoft"],
    whyThis: [
      "Tier-3 college reality: weak placement cells means most students need this playbook to find their first product co offer.",
      "40% of Indian product co hires are off-campus — Razorpay / Swiggy / CRED hire from LinkedIn / Naukri / referrals every month.",
      "FAANG India intern programs (Google STEP / Amazon WoW / MS Engage) are the highest-leverage off-campus paths — yet most students don't know they exist or miss application windows.",
      "Pair with Service / Product cracker roadmaps for the technical interview prep.",
    ],
    subjectSlugs: [
      "off-campus-playbook",
      "faang-india-prep",
      "resume-behavioural",
      "open-source-guide",
      "gsoc-india-playbook",
      "capstone-bank",
      "lld-design",
      "amcat-cocubes-elitmus",
      "mock-interview-comm",
      "final-layer-closures",
    ],
  },
  {
    slug: "backend-engineer",
    title: "Backend Engineer — Python / Go (12-40 LPA)",
    description:
      "FastAPI / Django / gin / fiber backend stack. Distinct from MERN (JS-only). Razorpay payments-core, Swiggy logistics, Atlan metadata service hire here. REST + gRPC + system design + LLD.",
    longDescription:
      "Indian product cos that aren't MERN-shop run on Python (FastAPI / Django) and Go (gin / fiber / chi). Razorpay's payments-core is Go, Swiggy's delivery-engine has Python services, Atlan runs Go microservices, Cred runs Python ML services. This roadmap front-loads Python (FastAPI primary, Django when CRUD-heavy) AND Go (the high-throughput option) — when each wins, how to pick. Pair with system design + LLD + DBMS + Networks + DevSecOps for senior-engineer interviews.",
    category: "Web Development",
    difficulty: "Intermediate",
    durationMonths: 6,
    subjectsCount: 9,
    topicsCount: 86,
    rating: 4.9,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "Python (FastAPI / Django)",
      "Go (gin / fiber / chi)",
      "REST + gRPC",
      "Async + goroutines",
      "DB integration (SQLAlchemy / GORM)",
      "Production deployment + observability",
    ],
    companies: ["razorpay", "swiggy", "atlan", "cred", "zerodha"],
    whyThis: [
      "Python + Go cover the backend gaps MERN doesn't — payments cores, ML services, high-throughput proxies.",
      "Go salary is +10-15% over equivalent Python role at fresher level (Razorpay / Atlan deltas).",
      "FastAPI + Pydantic deliver typed APIs with auto-OpenAPI — fast dev velocity at hiring-manager-level quality.",
      "Pairs naturally with the existing nodejs-backend (MERN) for full-stack JS/Python/Go optionality.",
    ],
    subjectSlugs: [
      "python-mastery",
      "backend-py-go",
      "database-sql",
      "dbms-complete",
      "mongodb-deep-dive",
      "system-design-basics",
      "lld-design",
      "networks-complete",
      "git-version-control",
    ],
  },
  {
    slug: "flutter-rn-developer",
    title: "Flutter / React Native Developer (6-22 LPA)",
    description:
      "Cross-platform mobile — Flutter (Dart + Riverpod + Bloc) or React Native (Hermes + Fabric + Zustand). When each wins. PhonePe / Paytm / Flipkart Lite use Flutter; Swiggy has RN. Cross-link to native android-kotlin.",
    longDescription:
      "Indian startups overwhelmingly hire cross-platform mobile engineers (Flutter or RN) instead of native Android + iOS — two engineers can't be hired for the budget of one cross-platform shipper. PhonePe runs Flutter, Paytm runs Flutter, Flipkart Lite runs Flutter; Swiggy / Discord-clones run React Native. This roadmap covers BOTH stacks in depth so a candidate can pick the best fit for the job spec. Pair with LLD (Repository / MVI patterns), system design, networks (offline-first sync), and Kotlin (for the native-fallback when cross-platform hits limits).",
    category: "Mobile",
    difficulty: "Intermediate",
    durationMonths: 5,
    subjectsCount: 5,
    topicsCount: 45,
    rating: 4.8,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "Flutter (Dart) + Riverpod + Bloc",
      "React Native + Hermes + Fabric",
      "State management (Zustand / Redux Toolkit)",
      "Native modules / platform channels",
      "Mobile testing + Play Store deployment",
    ],
    companies: ["phonepe", "paytm", "flipkart", "swiggy", "dream11"],
    whyThis: [
      "Cross-platform is the dominant mobile hiring pattern at Indian startups (cost-driven decision).",
      "Flutter + RN together cover ~80% of Indian mobile job specs — pick whichever the company uses.",
      "Pairs with the existing android-kotlin subject for the native-fallback cases.",
      "Lower entry bar than native Android — easier first-job pivot for tier-2/3 students.",
    ],
    subjectSlugs: [
      "cross-platform-mobile",
      "android-kotlin",
      "javascript-deep",
      "lld-design",
      "git-version-control",
    ],
  },
  {
    slug: "devsecops-engineer",
    title: "DevSecOps / AppSec Engineer (18-100 LPA)",
    description:
      "Highest-paid + lowest-supply Indian tech track. OWASP + STRIDE + SAST/DAST/SCA + container/K8s security + supply chain (SLSA / cosign / SBOM) + IAM + JWT pitfalls + incident response. Razorpay/Cred/Zerodha/HDFC Tech hire here.",
    longDescription:
      "AppSec / DevSecOps is the highest-paying + lowest-supply track in Indian tech in 2026. Razorpay, Cred, Zerodha, HDFC Tech, Goldman Sachs India, Wells Fargo Tech all hire dedicated AppSec engineers at 18-50 LPA fresher and 35-100 LPA mid-career. Demand-supply imbalance is roughly 10:1. The skill bar is real (RCE, SSRF, deserialization, supply-chain attacks) — but the compounding effect of being one of the few who can answer it is why the salary premium exists. Pair with the OS + Networks + Backend + K8s subjects for the full surface area.",
    category: "Security",
    difficulty: "Advanced",
    durationMonths: 8,
    subjectsCount: 7,
    topicsCount: 60,
    rating: 4.9,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "OWASP Top 10 + STRIDE",
      "SAST / DAST / SCA",
      "Container + K8s security",
      "Supply chain (SLSA / cosign / SBOM)",
      "IAM + zero trust",
      "Incident response",
    ],
    companies: ["razorpay", "cred", "zerodha", "hdfc-tech", "goldman-sachs"],
    whyThis: [
      "18-50 LPA fresher AppSec, 35-100 LPA mid-career — highest band in Indian tech outside FAANG senior eng.",
      "Demand-supply imbalance 10:1 in 2026 — every product co with payments / financial data needs AppSec but few engineers prep for it.",
      "Pairs with OS / Networks / Backend foundations — once those are deep, the AppSec layer is fast to add.",
      "Pivot path: SDE (2-3 yrs) → AppSec is real and well-trodden at Razorpay / Cred / GS India.",
    ],
    subjectSlugs: [
      "devsecops-appsec",
      "networks-complete",
      "os-complete",
      "system-design-basics",
      "kubernetes-orchestration",
      "cloud-platforms",
      "git-version-control",
    ],
  },
  {
    slug: "service-trio-cracker",
    title: "Cognizant + Capgemini + Wipro Cracker (3.5-7.6 LPA)",
    description:
      "3 service-co tests (~700k aspirants combined) in one roadmap. Aptitude × 3 + Python + service-trio playbook + Resume + Behavioural + HDFC banking tech tier-2 path. Apply broadly across Cognizant GenC / Capgemini Pseudocode / Wipro WILP.",
    longDescription:
      "Cognizant GenC (300k aspirants), Capgemini Pseudocode (200k), Wipro WILP / Elite NLTH (200k). Together these gate ~700k engineering hires per year. Aptitude foundation is shared with TCS NQT and Infosys SP — students who clear those are 80% prepared for these. This roadmap adds the trio-specific strategy: GenC Communication test, Capgemini's unique 8-game psychometric round, Wipro WILP's 5-year M.Tech-bond essay framework. The HDFC banking tech subject sits as a tier-2 fall-back — same aptitude prep applies, plus BFSI domain that opens HDFC / ICICI / SBI Tech / FIS / TCS BFSI funnels (~10k engineers/year, near-zero competition). Pair with Resume + Behavioural for the post-test rounds.",
    category: "Interview Prep",
    difficulty: "Beginner",
    durationMonths: 3,
    subjectsCount: 8,
    topicsCount: 63,
    rating: 4.8,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "Aptitude (Quant + Logical + Verbal)",
      "Python (coding rounds)",
      "Pseudocode reasoning",
      "Game-based aptitude (Pymetrics-style)",
      "Communication test (recorded video + essay)",
      "Resume + Behavioural STAR",
    ],
    companies: ["cognizant", "capgemini", "wipro"],
    whyThis: [
      "~700k aspirants per year — the third-biggest service-co bucket in India after TCS NQT and Infosys SP.",
      "Salary range 3.5-7.6 LPA, with premium tracks (GenC Next / Capgemini Senior Analyst / Wipro WILP M.Tech sponsorship).",
      "Aptitude prep cross-applies to TCS NQT + Infosys SP — students often attempt all 5.",
      "Capgemini's game-based round is unique — most students arrive unprepared. This roadmap closes that gap.",
    ],
    subjectSlugs: [
      "aptitude-quant",
      "aptitude-logical",
      "aptitude-verbal",
      "python-mastery",
      "cog-cap-wipro-playbook",
      "amcat-cocubes-elitmus",
      "hdfc-banking-tech",
      "resume-behavioural",
    ],
  },
  {
    slug: "gate-cse-cracker",
    title: "GATE CSE Cracker — IIT MTech / PSU / PhD",
    description:
      "200k aspirants/year. Subject-wise weightage + 12-month plan + PSU thresholds. Opens IIT/IISc MTech, PSU jobs (BHEL/IOCL/ONGC at 6-12 LPA + government benefits), PhD admissions. 80% syllabus overlap with product co interviews.",
    longDescription:
      "GATE CSE is the multi-path Indian engineering exam — the same 12 months of prep can land you an IIT MTech, a PSU job at ₹6-12 LPA + government benefits, OR a direct PhD admission. The topical syllabus (DBMS / OS / CN / COA / Compiler / TOC / Discrete Math / Algorithms) overlaps ~80% with product company core CS interviews, so GATE prep doubles as Razorpay/Flipkart/Goldman Sachs prep. This roadmap stitches together the existing core CS subjects (DBMS / OS / CN / Discrete Math + OOP) with the new Compiler + TOC subject and the GATE-specific tactical playbook.",
    category: "Interview Prep",
    difficulty: "Advanced",
    durationMonths: 12,
    subjectsCount: 9,
    topicsCount: 100,
    rating: 4.9,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "Algorithms + Discrete Math",
      "DBMS / OS / Networks deep",
      "COA + Digital Logic",
      "Compiler + TOC",
      "Mock test cadence (30+ full-length)",
      "PSU recruitment timing",
    ],
    companies: ["iit-bombay", "iit-delhi", "iisc", "bhel", "iocl", "ongc", "ntpc", "sail"],
    whyThis: [
      "200k aspirants/year — the prestige + PSU-prep test for engineering students.",
      "Multi-path: top 100 → IIT MTech, top 1000 → PSU jobs, indirect → product co interview prep.",
      "PSU jobs via GATE: ₹6-12 LPA + government benefits + job security — the rare premium-PSU combo.",
      "12-month prep timeline pairs with final-year studies — daily 3-hour cadence.",
    ],
    subjectSlugs: [
      "gate-cse",
      "discrete-math-oop",
      "dbms-complete",
      "os-complete",
      "networks-complete",
      "compiler-toc",
      "aptitude-quant",
      "aptitude-logical",
      "aptitude-verbal",
    ],
  },
  {
    slug: "embedded-iot-engineer",
    title: "Embedded / IoT Engineer (6-25 LPA)",
    description:
      "Hardware-startup wave (Ola Electric / Ather / Mahindra / Boat) + chip companies (Qualcomm / NXP / TI) + PSU (BHEL / BEL via GATE) + ISRO/DRDO. C/C++ + microcontrollers + RTOS + protocols + IoT cloud + bootloader/OTA.",
    longDescription:
      "Indian hardware-startup wave hires aggressively for embedded engineers. Ola Electric, Ather, Mahindra Electric, Boat, Tata Elxsi, KPIT, Capgemini Engineering, plus chip companies (Qualcomm India, NXP, TI, ARM India, Intel India, Marvell) — together they hire 5-10k embedded engineers annually. PSU pull (BHEL / BEL / DRDO / ISRO) via GATE adds a parallel premium-government path. This roadmap closes the embedded gap with C/C++ deep, microcontroller programming (STM32 + ESP32), FreeRTOS, all 5 protocols (UART/SPI/I2C/CAN/MQTT), Linux-on-embedded, AWS IoT cloud, OTA + code signing.",
    category: "Systems",
    difficulty: "Advanced",
    durationMonths: 7,
    subjectsCount: 6,
    topicsCount: 60,
    rating: 4.9,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "C / C++ for embedded",
      "Microcontrollers (STM32 / ESP32)",
      "FreeRTOS",
      "Communication protocols (UART/SPI/I2C/CAN/MQTT)",
      "IoT cloud (AWS IoT)",
      "Bootloader + OTA + code signing",
    ],
    companies: ["ola-electric", "ather", "mahindra", "boat", "qualcomm", "nxp", "ti"],
    whyThis: [
      "Hardware-startup wave: Ola Electric / Ather / Mahindra / Boat hire 5k+ embedded engineers/year.",
      "Chip cos at premium pay: Qualcomm India 15-25 LPA fresher, NXP / TI / Intel India 12-20 LPA.",
      "PSU pull (BHEL / BEL / DRDO / ISRO) via GATE adds government-track parallel path.",
      "C/C++ + FreeRTOS skills are language-stable — 10-year career-shelf without obsolescence anxiety.",
    ],
    subjectSlugs: [
      "embedded-iot",
      "cpp-mastery",
      "os-complete",
      "networks-complete",
      "system-design-basics",
      "git-version-control",
    ],
  },
  {
    slug: "game-dev-engineer",
    title: "Game Dev Engineer (Unity + Unreal) — 5-25 LPA",
    description:
      "Indian game industry track. Krafton (BGMI maker) at 15-25 LPA fresher, Dream11 + MPL + Junglee 6-13 LPA, Nazara 5-10 LPA. Unity (mobile + casual) + Unreal (AAA + console). C# + C++ + Blueprints + multiplayer.",
    longDescription:
      "Indian game industry hires 5k+ engineers per year — Krafton India (BGMI), Dream11 (fantasy gaming), MPL, Junglee Games, Nazara, Octro, Lila Games, Hi-Tech Animation, Ubisoft Pune. Unity dominates mobile + casual + indie; Unreal dominates AAA + console. This roadmap pairs the existing C++ Mastery + System Design + LLD with the new Game Dev subject, plus version control. Niche but real — and Krafton India salaries (15-25 LPA fresher) are at premium product-co levels.",
    category: "Game Dev",
    difficulty: "Intermediate",
    durationMonths: 6,
    subjectsCount: 5,
    topicsCount: 50,
    rating: 4.8,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "Unity (C# + MonoBehaviour)",
      "Unreal (C++ + Blueprints)",
      "Multiplayer (Mirror / Photon)",
      "3D math + shaders",
      "Mobile-game optimisation",
    ],
    companies: ["krafton", "dream11", "mpl", "junglee", "nazara"],
    whyThis: [
      "Indian game industry hires 5k+ engineers/year — Krafton India 15-25 LPA, MPL/Junglee 6-13 LPA, Nazara 5-10 LPA.",
      "Niche means low competition — fewer applicants per role at premium studios.",
      "C++ + LLD foundations carry over — game dev isn't a one-way career, you can pivot back to general engineering.",
      "Mobile-game economics in India are real (BGMI ecosystem, fantasy sports) — domain expertise compounds.",
    ],
    subjectSlugs: [
      "game-dev",
      "cpp-mastery",
      "lld-design",
      "system-design-basics",
      "git-version-control",
    ],
  },
  {
    slug: "blockchain-engineer",
    title: "Blockchain / Web3 Engineer (12-60 LPA)",
    description:
      "Indian Web3 — Polygon (unicorn), CoinDCX, Alephium, Nazara Web3. Ethereum + Solidity + Hardhat/Foundry + DeFi primitives + smart contract security + L2s. Volatile market, premium pay, niche supply.",
    longDescription:
      "Indian Web3 ecosystem is real despite the volatility — Polygon is an Indian unicorn (ZK rollups), CoinDCX is one of India's largest crypto exchanges, Nazara has a Web3 division, Reliance Jio is exploring Web3, plus a growing DeFi + NFT scene at smaller startups. Salaries are 12-30 LPA fresher Web3 engineer, 25-60 LPA mid-career — premium even compared to non-FAANG product co. The market is cyclical (2021 boom, 2022 winter, 2024 recovery) so timing matters. This roadmap covers Ethereum + Solidity + tooling (Hardhat/Foundry) + DeFi primitives + smart contract security + L2 scaling.",
    category: "Blockchain",
    difficulty: "Advanced",
    durationMonths: 6,
    subjectsCount: 4,
    topicsCount: 40,
    rating: 4.8,
    enrolled: 0,
    thumbnailAccent: "from-violet-500 to-cyan-500",
    skills: [
      "Ethereum + EVM internals",
      "Solidity (ERC-20 / 721 / 1155)",
      "Hardhat + Foundry tooling",
      "DeFi primitives (AMM / lending)",
      "Smart contract security",
      "L2 scaling (rollups)",
    ],
    companies: ["polygon", "coindcx", "alephium", "nazara"],
    whyThis: [
      "Premium pay despite volatility — 12-60 LPA bands at Indian Web3 cos.",
      "Indian regulatory clarity is improving (30% tax + 1% TDS) — companies are building globally first, India eventually.",
      "Smart contract security expertise is the most-portable — applies to any blockchain ecosystem.",
      "Nodejs-backend foundation transfers directly to dApp frontend / backend service.",
    ],
    subjectSlugs: [
      "blockchain-web3",
      "nodejs-backend",
      "devsecops-appsec",
      "git-version-control",
    ],
  },
];

export const ROADMAPS_BY_SLUG: Record<string, Roadmap> = Object.fromEntries(
  ROADMAPS.map((r) => [r.slug, r]),
);

export function getRoadmap(slug: string): Roadmap | undefined {
  return ROADMAPS_BY_SLUG[slug];
}

/* ============================================================================
 *  Roadmap chain map — sensible "next track" suggested when a learner
 *  finishes a roadmap. Surfaced by subject-markdown-reader's end-of-roadmap
 *  card to drive cross-roadmap discovery (highest engagement lever).
 *
 *  Order: each entry maps "if you just finished X, try Y next."
 *  Some chains are linear (Service → Product → MERN → Backend); others are
 *  side-grades (Android → Flutter/RN). DevSecOps is a terminus — no obvious
 *  next step at that altitude.
 * ============================================================================
 */
const NEXT_ROADMAP: Record<string, string> = {
  // Indian-exam ladder
  "tcs-nqt-cracker": "service-company-cracker",
  "infosys-sp-cracker": "service-company-cracker",
  "service-trio-cracker": "service-company-cracker",
  "service-company-cracker": "product-company-cracker",
  "off-campus-cracker": "product-company-cracker",
  "gate-cse-cracker": "product-company-cracker",
  // Product-company → specialisation tracks
  "product-company-cracker": "mern-stack-developer",
  "mern-stack-developer": "backend-engineer",
  "backend-engineer": "devsecops-engineer",
  // Mobile side-grade
  "android-developer": "flutter-rn-developer",
  "flutter-rn-developer": "android-developer",
  // Frontend → full-stack
  "senior-frontend-engineer": "mern-stack-developer",
  // Java full stack → cloud/devops
  "java-full-stack": "cloud-devops-engineer",
  "cloud-devops-engineer": "devsecops-engineer",
  // Data ladder
  "data-analyst-top2": "data-engineer",
  "data-engineer": "ml-engineer",
  "ml-engineer": "genai-developer",
  // QA upgrade path
  "qa-sdet-cracker": "backend-engineer",
  // Niche → security
  "embedded-iot-engineer": "devsecops-engineer",
  "blockchain-engineer": "devsecops-engineer",
  "game-dev-engineer": "flutter-rn-developer",
  // Portfolio is independent — when finished, push to product-cracker
  "portfolio-builder": "product-company-cracker",
};

/**
 *  Returns the suggested follow-up Roadmap for the given slug, or undefined
 *  if the chain ends here (e.g., devsecops-engineer or genai-developer are
 *  termini in their respective ladders).
 */
export function getNextRoadmap(slug: string): Roadmap | undefined {
  const nextSlug = NEXT_ROADMAP[slug];
  return nextSlug ? ROADMAPS_BY_SLUG[nextSlug] : undefined;
}
